version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 30s
      timeout: 10s
      retries: 3

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 3

  producer:
    build:
      context: .
      dockerfile: docker/Dockerfile.producer
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    restart: on-failure
    command: python src/producer.py

  consumer:
    build:
      context: .
      dockerfile: docker/Dockerfile.consumer
    depends_on:
      - producer
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    restart: on-failure
    command: python src/consumer.py

  trainer:
    build:
      context: .
      dockerfile: docker/Dockerfile.trainer
    depends_on:
      - consumer
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    restart: "no"
    command: >
      sh -c "sleep 120 && python src/trainer.py"

  # Update bagian api:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    depends_on:
      - trainer
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    ports:
      - "8000:8000"
    restart: on-failure
    command: ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "info"]